engines:
  checkstyle:
    enabled: true 
    config: 'config/checkstyle/checkstyle.xml'
    channel: 'beta'
  pmd:
      enabled: true
      config: 'config/pmd/pmd.xml'
      channel: 'beta'
      rulesets: [
        "java-unusedcode",
        "java-imports"
      ]
      reports: [
        "xml"
      ]
      paths:  [
         "**.java"
         ]
ratings:
   paths:  [
   "**.java"
   ]
exclude_paths: [
  "build/",
  "**/test/",
  "**/exceptions/",
  "mediation.adaters/",
  "**/demo/",
  "**/model/"
]